// <auto-generated />
using System;
using AuthUserServiceInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthUserServiceInfrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804093724_c8")]
    partial class c8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthUserServiceDomain.Models.RefreshTokens", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AuthUserServiceDomain.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BrokersClients", b =>
                {
                    b.Property<int>("BrokersId")
                        .HasColumnType("int");

                    b.Property<int>("ClientsId")
                        .HasColumnType("int");

                    b.HasKey("BrokersId", "ClientsId");

                    b.HasIndex("ClientsId");

                    b.ToTable("BrokersClients");
                });

            modelBuilder.Entity("AuthUserServiceDomain.Models.Admins", b =>
                {
                    b.HasBaseType("AuthUserServiceDomain.Models.Users");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("AuthUserServiceDomain.Models.Brokers", b =>
                {
                    b.HasBaseType("AuthUserServiceDomain.Models.Users");

                    b.ToTable("Brokers", (string)null);
                });

            modelBuilder.Entity("AuthUserServiceDomain.Models.Clients", b =>
                {
                    b.HasBaseType("AuthUserServiceDomain.Models.Users");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("AuthUserServiceDomain.Models.RefreshTokens", b =>
                {
                    b.HasOne("AuthUserServiceDomain.Models.Users", "User")
                        .WithOne()
                        .HasForeignKey("AuthUserServiceDomain.Models.RefreshTokens", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrokersClients", b =>
                {
                    b.HasOne("AuthUserServiceDomain.Models.Brokers", null)
                        .WithMany()
                        .HasForeignKey("BrokersId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("AuthUserServiceDomain.Models.Clients", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthUserServiceDomain.Models.Admins", b =>
                {
                    b.HasOne("AuthUserServiceDomain.Models.Users", null)
                        .WithOne()
                        .HasForeignKey("AuthUserServiceDomain.Models.Admins", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthUserServiceDomain.Models.Brokers", b =>
                {
                    b.HasOne("AuthUserServiceDomain.Models.Users", null)
                        .WithOne()
                        .HasForeignKey("AuthUserServiceDomain.Models.Brokers", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthUserServiceDomain.Models.Clients", b =>
                {
                    b.HasOne("AuthUserServiceDomain.Models.Users", null)
                        .WithOne()
                        .HasForeignKey("AuthUserServiceDomain.Models.Clients", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
